name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Ce pipeline s'exécute à chaque push sur la branche main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Récupérer le code du dépôt
    - name: Checkout code
      uses: actions/checkout@v2

    # Étape 2 : Se connecter à Docker Hub en utilisant les identifiants secrets
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Étape 3 : Construire l'image Docker
    - name: Build Docker image
      run: docker build -t muhire96/loan-api:v1 .

    # Étape 4 : Pousser l'image Docker sur Docker Hub
    - name: Push Docker image
      run: docker push muhire96/loan-api:v1
